#!/bin/bash

if [ $# -eq 1 ] && [ "$1" == "--help" ]; then
    echo "\
Calls the C coding style checker (banana)

    Without arguments:  on the current directory.
    With arguments:     on the first argument."
    exit
fi

# Delete old log
sudo rm -rf /tmp/coding-style-reports.log

if [ $# -eq 0 ]; then
    banana . /tmp/
else
    banana "$1" /tmp/
fi
clear
cat /tmp/coding-style-reports.log
