#!/bin/bash

if [ $# -eq 1 ]; then
    docker run -it --name epitech -v "$1":/data -w /data epitechcontent/epitest-docker
else
    docker run -it --name epitech -v "$(pwd)":/data -w /data epitechcontent/epitest-docker
fi

docker rm epitech > /dev/null